suppress warning, add meson ninja, test pkg-config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -534,7 +534,7 @@ jobs:
         if: runner.os == 'Windows'
         shell: msys2 {0}
         run: |
-          mv /C/Strawberry/perl/bin/pkg-config.BAT /C/Strawberry/perl/bin/pkg-config-strawberry.BAT
+          mv /C/Strawberry /C/StrawberryTEMP
 
       - name: Configure PETSc
         if: runner.os == 'Linux'
@@ -559,7 +559,11 @@ jobs:
           pacman -Sy --noconfirm autoconf automake-wrapper bison bsdcpio make git \
             mingw-w64-x86_64-toolchain patch python flex \
             pkg-config pkgfile tar unzip mingw-w64-x86_64-cmake \
-            mingw-w64-x86_64-msmpi mingw-w64-x86_64-openblas mingw-w64-x86_64-jq
+            mingw-w64-x86_64-msmpi mingw-w64-x86_64-openblas mingw-w64-x86_64-jq \
+            meson ninja
+          pkg-config petsc
+          pkg-config mpi
+          pkg-config msmpi
 
       - name: Configure PETSc
         if: runner.os == 'Windows'
@@ -567,7 +571,7 @@ jobs:
         working-directory: petsc
         run: |
           export PETSC_ARCH=arch-msys-msmpi
-          /usr/bin/python ./configure --with-mpiexec='/C/Program\ Files/Microsoft\ MPI/Bin/mpiexec' --with-shared-libraries=0 --with-cxx=0 --CFLAGS=-Wno-format
+          /usr/bin/python ./configure --with-mpiexec='/C/Program\ Files/Microsoft\ MPI/Bin/mpiexec' --with-shared-libraries=0 --with-cxx=0 --CFLAGS='-Wno-format -Wno-stringop-overflow'
 
       - name: Build PETSc
         if: runner.os == 'Windows'
@@ -577,44 +581,44 @@ jobs:
           make all
           make check
 
-      - name: Setup Micromamba
-        uses: mamba-org/setup-micromamba@v1
-        with:
-          environment-file: modflow6/environment.yml
-          init-shell: >-
-            bash
-            powershell
-          cache-environment: true
-          cache-downloads: true
+      # - name: Setup Micromamba
+      #   uses: mamba-org/setup-micromamba@v1
+      #   with:
+      #     environment-file: modflow6/environment.yml
+      #     init-shell: >-
+      #       bash
+      #       powershell
+      #     cache-environment: true
+      #     cache-downloads: true
 
-      - name: Build modflow6
-        working-directory: modflow6
-        run: |
-          meson setup builddir -Ddebug=false -Dparallel=true --prefix=$(pwd) --libdir=bin
-          meson install -C builddir
-          meson test --verbose --no-rebuild -C builddir
+      # - name: Build modflow6
+      #   working-directory: modflow6
+      #   run: |
+      #     meson setup builddir -Ddebug=false -Dparallel=true --prefix=$(pwd) --libdir=bin
+      #     meson install -C builddir
+      #     meson test --verbose --no-rebuild -C builddir
 
-      - name: Show Meson logs
-        if: failure()
-        working-directory: modflow6
-        run: cat builddir/meson-logs/meson-log.txt
+      # - name: Show Meson logs
+      #   if: failure()
+      #   working-directory: modflow6
+      #   run: cat builddir/meson-logs/meson-log.txt
 
-      - name: Update flopy
-        working-directory: modflow6/autotest
-        run: python update_flopy.py
+      # - name: Update flopy
+      #   working-directory: modflow6/autotest
+      #   run: python update_flopy.py
 
-      - name: Get executables
-        working-directory: modflow6/autotest
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-        run: pytest -v --durations 0 get_exes.py
+      # - name: Get executables
+      #   working-directory: modflow6/autotest
+      #   env:
+      #     GITHUB_TOKEN: ${{ github.token }}
+      #   run: pytest -v --durations 0 get_exes.py
 
-      - name: Test programs (parallel)
-        working-directory: modflow6/autotest
-        env:
-          REPOS_PATH: ${{ github.workspace }}
-        run: |
-          branch="${{ github.ref_name }}"
-          marker="not large"
-          markers=$([ "$branch" == "master" ] && echo "$marker and not developmode" || echo "$marker")
-          pytest -v -n auto --parallel --durations 0 -m "$markers"
+      # - name: Test programs (parallel)
+      #   working-directory: modflow6/autotest
+      #   env:
+      #     REPOS_PATH: ${{ github.workspace }}
+      #   run: |
+      #     branch="${{ github.ref_name }}"
+      #     marker="not large"
+      #     markers=$([ "$branch" == "master" ] && echo "$marker and not developmode" || echo "$marker")
+      #     pytest -v -n auto --parallel --durations 0 -m "$markers"
